### PR TITLE
Fix reset quality gate action not showing up for jobs in folders

### LINKED ISSUE #3176: [JENKINS-75588] Quality gate "Reset" button not showing for jobs under GitHub Organization Folder
<p>When using the Warnings NG plugin with jobs inside a GitHub Organization Folder, the "Reset Quality Gate" button does not appear in the build UI, even when a quality gate is triggered. This issue does not occur with standalone jobs or multibranch pipeline jobs outside of Organization Folders.</p>

<p><b>Steps to Reproduce</b>:</p>
<ol>
	<li>Create a GitHub Organization Folder.</li>
	<li>Allow it to scan and create repository jobs.</li>
	<li>Configure a job to use the Warnings NG plugin and trigger a quality gate.</li>
	<li>Navigate to a build where the gate fails or triggers.</li>
	<li>Observe that the "Reset Quality Gate" button is missing from the UI.</li>
</ol>

<p><b>Expected Behavior</b>:<br/>
The "Reset Quality Gate" button should be visible in the build UI if a quality gate has been triggered, regardless of the job being in an Organization Folder.</p>

<p><b>Actual Behavior</b>:<br/>
The button does not show for builds under jobs created via Organization Folders, making it impossible to manually reset the gate from the UI.</p>

<p><b>Additional Info</b>:<br/>
Jenkins version: 2.492.3<br/>
Warnings NG plugin version: 12.5.0<br/>
Job type: WorkflowJob under a GitHub Organization Folder<br/>
User has full permissions.</p>

<p>Here are screenshots of 3 jobs used to reproduce the error:</p>

<p><em>Org Folder Job (This is the issue)</em><br/>
<em><span class="image-wrap" style=""></span></em></p>

<p><em>Standalone multibranch pipeline</em><br/>
<em><span class="image-wrap" style=""></span></em></p>

<p><em>Standalone pipeline</em><br/>
<em><span class="image-wrap" style=""></span></em></p>

<p>They are all checking out the same repo with this pipeline:</p>

<pre>
pipeline {
  agent {
    label <span class="code-quote">'ubuntu-small'</span>
  }
  stages {
    stage( <span class="code-quote">"Create Warning file"</span> ) {
      steps {
        sh '''
          echo <span class="code-quote">"warnings.txt(1): warning W1: New warning exists"</span> >> warnings.txt
          echo <span class="code-quote">"warnings.txt(2): warning W1: New warning exists"</span> >> warnings.txt
          echo <span class="code-quote">"warnings.txt(3): warning W1: New warning exists"</span> >> warnings.txt
        '''
      }
    }
    stage( <span class="code-quote">"Warnings"</span> ) {
      steps {
        discoverReferenceBuild referenceJob: env.JOB_NAME
        recordIssues(tools: [msBuild([pattern:<span class="code-quote">'warnings.txt'</span>, id:<span class="code-quote">'real-target-msbuild-cds'</span>, name:<span class="code-quote">"${env.STAGE_NAME} Construction Design Scope MSBuild"</span>])],
         qualityGates:[[threshold:2,type:<span class="code-quote">'NEW'</span>,unstable:<span class="code-keyword">true</span>]])
      }
    }
  }
} </pre>
<p>Any help is much appreciated.</p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=benitezlalom">benitezlalom</a>, imported from: <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-75588" target="_blank">Quality gate "Reset" button not showing for jobs under GitHub Organization Folder</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>component(s)</b>: warnings-ng-plugin
<li><b>label(s)</b>: help-wanted
<li><b>resolution</b>: Unresolved
<li><b>votes</b>: 0
<li><b>watchers</b>: 2
<li><b>imported</b>: 2025-12-09
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>When using the Warnings NG plugin with jobs inside a GitHub Organization Folder, the "Reset Quality Gate" button does not appear in the build UI, even when a quality gate is triggered. This issue does not occur with standalone jobs or multibranch pipeline jobs outside of Organization Folders.</p>

<p><b>Steps to Reproduce</b>:</p>
<ol>
	<li>Create a GitHub Organization Folder.</li>
	<li>Allow it to scan and create repository jobs.</li>
	<li>Configure a job to use the Warnings NG plugin and trigger a quality gate.</li>
	<li>Navigate to a build where the gate fails or triggers.</li>
	<li>Observe that the "Reset Quality Gate" button is missing from the UI.</li>
</ol>

<p><b>Expected Behavior</b>:
The "Reset Quality Gate" button should be visible in the build UI if a quality gate has been triggered, regardless of the job being in an Organization Folder.</p>

<p><b>Actual Behavior</b>:
The button does not show for builds under jobs created via Organization Folders, making it impossible to manually reset the gate from the UI.</p>

<p><b>Additional Info</b>:
Jenkins version: 2.492.3
Warnings NG plugin version: 12.5.0
Job type: WorkflowJob under a GitHub Organization Folder
User has full permissions.</p>

<p>Here are screenshots of 3 jobs used to reproduce the error:</p>

<p><em>Org Folder Job (This is the issue)</em>
<em><span class="image-wrap" style=""></span></em></p>

<p><em>Standalone multibranch pipeline</em>
<em><span class="image-wrap" style=""></span></em></p>

<p><em>Standalone pipeline</em>
<em><span class="image-wrap" style=""></span></em></p>

<p>They are all checking out the same repo with this pipeline:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">pipeline {
  agent {
    label <span class="code-quote">'ubuntu-small'</span>
  }
  stages {
    stage( <span class="code-quote">"Create Warning file"</span> ) {
      steps {
        sh '''
          echo <span class="code-quote">"warnings.txt(1): warning W1: New warning exists"</span> &gt;&gt; warnings.txt
          echo <span class="code-quote">"warnings.txt(2): warning W1: New warning exists"</span> &gt;&gt; warnings.txt
          echo <span class="code-quote">"warnings.txt(3): warning W1: New warning exists"</span> &gt;&gt; warnings.txt
        '''
      }
    }
    stage( <span class="code-quote">"Warnings"</span> ) {
      steps {
        discoverReferenceBuild referenceJob: env.JOB_NAME
        recordIssues(tools: [msBuild([pattern:<span class="code-quote">'warnings.txt'</span>, id:<span class="code-quote">'real-target-msbuild-cds'</span>, name:<span class="code-quote">"${env.STAGE_NAME} Construction Design Scope MSBuild"</span>])],
         qualityGates:[[threshold:2,type:<span class="code-quote">'NEW'</span>,unstable:<span class="code-keyword">true</span>]])
      }
    }
  }
} </pre>
</div></div>
<p>Any help is much appreciated.</p></pre>
</details>
</details>
<details><summary><i>environment</i></summary>

```
Jenkins: 2.492.3<br/>
OS: Linux - 4.14.348-265.565.amzn2.x86_64<br/>
Java: 21.0.6 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)<br/>
---<br/>
Exclusion:0.15<br/>
Matrix-sorter-plugin:1.3<br/>
Office-365-Connector:5.1.0<br/>
PrioritySorter:849.v459ea_77d16d4<br/>
analysis-model-api:13.2.0<br/>
ansicolor:1.0.6<br/>
ant:513.vde9e7b_a_0da_0f<br/>
antisamy-markup-formatter:173.v680e3a_b_69ff3<br/>
any-buildstep:14.ve115ec1484f0<br/>
apache-httpcomponents-client-4-api:4.5.14-269.vfa_2321039a_83<br/>
apache-httpcomponents-client-5-api:5.4.3-140.v2516ccde99e7<br/>
artifact-manager-s3:902.v39b_3d56b_88b_5<br/>
artifactory:4.0.8<br/>
asm-api:9.8-135.vb_2239d08ee90<br/>
audit-trail:395.vce180b_359a_b_5<br/>
authentication-tokens:1.131.v7199556c3004<br/>
authorize-project:2.0.0<br/>
aws-credentials:245.v8a_1b_7c11a_94d<br/>
aws-global-configuration:144.v1b_4447b_7c93e<br/>
aws-java-sdk:1.12.780-480.v4a_0819121a_9e<br/>
aws-java-sdk-api-gateway:1.12.780-480.v4a_0819121a_9e<br/>
aws-java-sdk-autoscaling:1.12.780-480.v4a_0819121a_9e<br/>
aws-java-sdk-cloudformation:1.12.780-480.v4a_0819121a_9e<br/>
aws-java-sdk-cloudfront:1.12.780-480.v4a_0819121a_9e<br/>
aws-java-sdk-cloudwatch:1.12.780-480.v4a_0819121a_9e<br/>
aws-java-sdk-codebuild:1.12.780-480.v4a_0819121a_9e<br/>
aws-java-sdk-codedeploy:1.12.780-480.v4a_0819121a_9e<br/>
aws-java-sdk-ec2:1.12.780-480.v4a_0819121a_9e<br/>
aws-java-sdk-ecr:1.12.780-480.v4a_0819121a_9e<br/>
aws-java-sdk-ecs:1.12.780-480.v4a_0819121a_9e<br/>
aws-java-sdk-efs:1.12.780-480.v4a_0819121a_9e<br/>
aws-java-sdk-elasticbeanstalk:1.12.780-480.v4a_0819121a_9e<br/>
aws-java-sdk-elasticloadbalancingv2:1.12.780-480.v4a_0819121a_9e<br/>
aws-java-sdk-iam:1.12.780-480.v4a_0819121a_9e<br/>
aws-java-sdk-kinesis:1.12.780-480.v4a_0819121a_9e<br/>
aws-java-sdk-lambda:1.12.780-480.v4a_0819121a_9e<br/>
aws-java-sdk-logs:1.12.780-480.v4a_0819121a_9e<br/>
aws-java-sdk-minimal:1.12.780-480.v4a_0819121a_9e<br/>
aws-java-sdk-organizations:1.12.780-480.v4a_0819121a_9e<br/>
aws-java-sdk-secretsmanager:1.12.780-480.v4a_0819121a_9e<br/>
aws-java-sdk-sns:1.12.780-480.v4a_0819121a_9e<br/>
aws-java-sdk-sqs:1.12.780-480.v4a_0819121a_9e<br/>
aws-java-sdk-ssm:1.12.780-480.v4a_0819121a_9e<br/>
aws-java-sdk2-core:2.30.28-26.v649b_8df2f988<br/>
aws-java-sdk2-ec2:2.30.28-26.v649b_8df2f988<br/>
aws-secrets-manager-credentials-provider:1.214.va_0a_d8268d068<br/>
aws-secrets-manager-secret-source:1.72.v61781b_35c542<br/>
azure-credentials:357.v6447d38fb_007<br/>
azure-sdk:206.v7df6fdd1d0ff<br/>
azure-vm-agents:1013.v7a_2a_cd831714<br/>
badge:2.8<br/>
basic-branch-build-strategies:228.v68c089762a_db_<br/>
blueocean:1.27.17<br/>
blueocean-autofavorite:1.2.5<br/>
blueocean-bitbucket-pipeline:1.27.17<br/>
blueocean-commons:1.27.17<br/>
blueocean-config:1.27.17<br/>
blueocean-core-js:1.27.17<br/>
blueocean-dashboard:1.27.17<br/>
blueocean-display-url:2.4.4<br/>
blueocean-events:1.27.17<br/>
blueocean-git-pipeline:1.27.17<br/>
blueocean-github-pipeline:1.27.17<br/>
blueocean-i18n:1.27.17<br/>
blueocean-jira:1.27.17<br/>
blueocean-jwt:1.27.17<br/>
blueocean-personalization:1.27.17<br/>
blueocean-pipeline-api-impl:1.27.17<br/>
blueocean-pipeline-editor:1.27.17<br/>
blueocean-pipeline-scm-api:1.27.17<br/>
blueocean-rest:1.27.17<br/>
blueocean-rest-impl:1.27.17<br/>
blueocean-web:1.27.17<br/>
bootstrap5-api:5.3.3-2<br/>
bouncycastle-api:2.30.1.80-256.vf98926042a_9b_<br/>
branch-api:2.1217.v43d8b_b_d8b_2c7<br/>
build-cause-run-condition:0.1<br/>
build-keeper-plugin:19.va_df8a_2c65123<br/>
build-monitor-plugin:1.14-973.ve458d62e7c4f<br/>
build-name-setter:2.5.0<br/>
build-timeout:1.38<br/>
build-user-vars-plugin:195.v8c35f9d5c3dc<br/>
buildresult-trigger:1.01<br/>
built-on-column:1.5<br/>
caffeine-api:3.2.0-166.v72a_6d74b_870f<br/>
categorized-view:168.v121c7e2fa_2b_b_<br/>
checks-api:367.v18b_7f530e54a_<br/>
chucknorris:159.vdfe649cb_9c37<br/>
claim:599.v95c2f92e1c88<br/>
cloud-stats:377.vd8a_6c953e98e<br/>
cloudbees-bitbucket-branch-source:935.1.3<br/>
cloudbees-folder:6.1012.v79a_86a_1ea_c1f<br/>
clover:4.14.2.628.ve412b_714e733<br/>
cobertura:1.17<br/>
code-coverage-api:4.99.0<br/>
command-launcher:123.v37cfdc92ef67<br/>
commons-compress-api:1.27.1-3<br/>
commons-httpclient3-api:3.1-3<br/>
commons-lang3-api:3.17.0-87.v5cf526e63b_8b_<br/>
commons-text-api:1.13.0-153.v91dcd89e2a_22<br/>
computer-queue-plugin:1.7<br/>
conditional-buildstep:1.5.0<br/>
config-file-provider:982.vb_a_e458a_37021<br/>
configuration-as-code:1953.v148f87d74b_1e<br/>
configuration-as-code-groovy:1.1<br/>
copy-project-link:106.veb_028794a_844<br/>
copyartifact:765.v0357cc6e6eb_3<br/>
coverage:2.4.0<br/>
cppncss:1.2<br/>
credentials:1413.va_51c53703df1<br/>
credentials-binding:687.v619cb_15e923f<br/>
cucumber-reports:5.8.5<br/>
custom-tools-plugin:0.8<br/>
cvs:476.v1a_f0c9e7e218<br/>
dashboard-view:2.528.v3470c02b_d7c9<br/>
data-tables-api:2.2.2-1<br/>
datetime-constraint:0.1.2<br/>
delivery-pipeline-plugin:1.4.2<br/>
depgraph-view:1.0.5<br/>
description-setter:1.10-CUSTOM<br/>
disable-github-multibranch-status:1.2<br/>
display-url-api:2.209.v582ed814ff2f<br/>
docker-commons:451.vd12c371eeeb_3<br/>
docker-workflow:611.v16e84da_6d3ff<br/>
downstream-ext:73.vdda_16e6eb_0da<br/>
dropdown-viewstabbar-plugin:1.7<br/>
dtkit-api:3.0.3<br/>
durable-task:587.v84b_877235b_45<br/>
dynamic-axis:1.0.3<br/>
ec2:1891.v03c1282cf236<br/>
echarts-api:5.6.0-3<br/>
ecutest:2.44<br/>
eddsa-api:0.3.0.1-19.vc432d923e5ee<br/>
email-ext:1876.v28d8d38315b_d<br/>
embeddable-build-status:548.v5653c6e28c41<br/>
emoji-symbols-api:16.0-26.v9818ff7423f0<br/>
envinject:2.926.v69c9b_3896a_96<br/>
envinject-api:1.235.va_14c74f8f487<br/>
environment-variable-page-decoration:1.3.0<br/>
excludeMatrixParent:1.1<br/>
extended-choice-parameter:388.ve7b_d0b_920e10<br/>
extended-read-permission:61.vf24570ff3b_e9<br/>
extensible-choice-parameter:237.v51568f37b_78e<br/>
external-monitor-job:223.vb_fddcf42c9b_3<br/>
external-workspace-manager:1.3.1<br/>
ez-templates:1.3.5<br/>
favorite:2.225.v68765b_b_a_1fa_3<br/>
file-parameters:367.vc2cc39fb_b_593<br/>
fitnesse:1.36<br/>
flexible-publish:0.16.1<br/>
font-awesome-api:6.7.2-1<br/>
forensics-api:3.1.0<br/>
git:5.7.0<br/>
git-client:6.1.3<br/>
git-forensics:3.2.0<br/>
git-parameter:435.va_f85861c663a_<br/>
git-server:137.ve0060b_432302<br/>
github:1.43.0<br/>
github-api:1.321-488.v9b_c0da_9533f8<br/>
github-autostatus:3.6.2<br/>
github-branch-source:1815.v9152b_2ff7a_1b_<br/>
github-issues:1.2.4<br/>
github-oauth:651.v135e939e8b_60<br/>
github-scm-trait-commit-skip:0.4.0<br/>
google-oauth-plugin:1.335.ve6de40e2db_18<br/>
gradle:2.14.1<br/>
groovy:497.v7b_061a_a_de65d<br/>
groovy-postbuild:272.v52a_03efb_8653<br/>
gson-api:2.13.0-133.v5a_e3236a_8251<br/>
h2-api:11.1.4.199-36.vb_ee07e965744<br/>
handy-uri-templates-2-api:2.1.8-36.v85e4cb_234a_13<br/>
htmlpublisher:425<br/>
hubot-steps:95.va_30176518a_5a<br/>
instance-identity:203.v15e81a_1b_7a_38<br/>
ionicons-api:82.v0597178874e1<br/>
ivy:582.v35fb_da_0312f7<br/>
jackson2-api:2.18.3-402.v74c4eb_f122b_2<br/>
jacoco:3.3.7<br/>
jakarta-activation-api:2.1.3-2<br/>
jakarta-mail-api:2.1.3-2<br/>
javadoc:327.vdfe586651ee0<br/>
javax-activation-api:1.2.0-8<br/>
javax-mail-api:1.6.2-11<br/>
jaxb:2.3.9-133.vb_ec76a_73f706<br/>
jdk-tool:83.v417146707a_3d<br/>
jenkins-design-language:1.27.17<br/>
jenkins-metrics-sender:0.01-SNAPSHOT (private-1926b506-?)<br/>
jersey2-api:2.45-154.v4ded3dc34f81<br/>
jfrog:1.5.8<br/>
jira:3.14<br/>
jjwt-api:0.11.5-120.v0268cf544b_89<br/>
jnr-posix-api:3.1.20-138.vdb_9db_a_39182f<br/>
job-dsl:1.91<br/>
job-restrictions:216.v0732cc7fb_076<br/>
jobConfigHistory:1305.vf20a_356586b_8<br/>
joda-time-api:2.14.0-127.v7d9da_295a_d51<br/>
jquery:1.12.4-3<br/>
jquery3-api:3.7.1-3<br/>
jsch:0.2.16-95.v3eecb_55fa_b_78<br/>
json-api:20250107-125.v28b_a_ffa_eb_f01<br/>
json-path-api:2.9.0-148.v22a_7ffe323ce<br/>
jsoup:1.19.1-38.v216a_f3721b_3c<br/>
junit:1322.v1556dc1c59a_f<br/>
junit-attachments:299.v2e00f511b_538<br/>
keepSlaveOffline:1.0<br/>
kubernetes:4324.vfec199a_33512<br/>
kubernetes-client-api:6.10.0-251.v556f5f100500<br/>
kubernetes-credentials:192.v4d5b_1c429d17<br/>
label-verifier:116.vb_845759df630<br/>
ldap:780.vcb_33c9a_e4332<br/>
locale:566.v3323643741cc<br/>
lockable-resources:1349.v8b_ccb_c5487f7<br/>
log-parser:2.3.7<br/>
logstash:2.5.0218.v0a_ff8fefc12b_<br/>
mailer:489.vd4b_25144138f<br/>
mapdb-api:1.0.9-44.va_1e1310c9118<br/>
mask-passwords:188.v66e477dcb_24a_<br/>
matrix-auth:3.2.6<br/>
matrix-combinations-parameter:1.3.3<br/>
matrix-project:847.v88a_f90ff9f20<br/>
maven-plugin:3.25<br/>
measurement-plots:0.1<br/>
mercurial:1309.v6802b_f0efb_b_9<br/>
metrics:4.2.21-464.vc9fa_a_0d6265d<br/>
mina-sshd-api-common:2.15.0-161.vb_200831a_c15b_<br/>
mina-sshd-api-core:2.15.0-161.vb_200831a_c15b_<br/>
mina-sshd-api-scp:2.15.0-161.vb_200831a_c15b_<br/>
monitoring:2.5.0<br/>
multi-branch-priority-sorter:1.0<br/>
multibranch-action-triggers:1.8.10<br/>
multibranch-build-strategy-extension:61.vf6d8f6f5ed02<br/>
nested-view:1.36<br/>
next-build-number:66.v4b_4762172d53<br/>
node-iterator-api:72.vc90e81737df1<br/>
nodelabelparameter:759.vb_b_e95db_f3251<br/>
oauth-credentials:0.657.v7d8dd90b_0382<br/>
offlineonfailure-plugin:1.1-SNAPSHOT (private-03/11/2016 13:37-gsix)<br/>
okhttp-api:4.11.0-189.v976fa_d3379d6<br/>
oss-symbols-api:318.ve82d80c8e1c4<br/>
pam-auth:1.12<br/>
parameterized-scheduler:285.ve611986d4c48<br/>
parameterized-trigger:840.v3c7d4a_a_5e6c7<br/>
pipeline-aggregator-view:119.v4b_ec11953552<br/>
pipeline-build-step:567.vea_ce550ece97<br/>
pipeline-github:2.8-162.382498405fdc<br/>
pipeline-github-lib:65.v203688e7727e<br/>
pipeline-githubnotify-step:49.vf37bf92d2bc8<br/>
pipeline-graph-analysis:235.vb_a_a_36b_f248c2<br/>
pipeline-groovy-lib:752.vdddedf804e72<br/>
pipeline-input-step:517.vf8e782ee645c<br/>
pipeline-maven:1508.v347c4b_692202<br/>
pipeline-maven-api:1508.v347c4b_692202<br/>
pipeline-milestone-step:127.vb_52887ca_3b_6d<br/>
pipeline-model-api:2.2254.v2a_978de46f35<br/>
pipeline-model-definition:2.2254.v2a_978de46f35<br/>
pipeline-model-extensions:2.2254.v2a_978de46f35<br/>
pipeline-multibranch-defaults:2.1<br/>
pipeline-rest-api:2.37<br/>
pipeline-stage-step:322.vecffa_99f371c<br/>
pipeline-stage-tags-metadata:2.2254.v2a_978de46f35<br/>
pipeline-stage-view:2.37<br/>
pipeline-timeline:1.0.3<br/>
pipeline-utility-steps:2.19.0<br/>
plain-credentials:195.vb_906e9073dee<br/>
plot:2.4.0<br/>
plugin-usage-plugin:4.10<br/>
plugin-util-api:6.1.0<br/>
pollscm:1.9<br/>
postbuild-task:72.v75dc459e4747<br/>
postbuildscript:3.4.1-695.vf6b_0b_8053979<br/>
preSCMbuildstep:115.vf9808414429d<br/>
prism-api:1.30.0-1<br/>
progress-bar-column-plugin:11.vdef198c2d6c1<br/>
project-description-setter:1.2<br/>
project-health-report:1.2<br/>
promoted-builds:984.v90b_eb_99fc7b_4<br/>
publish-over:0.22<br/>
publish-over-cifs:0.16<br/>
pubsub-light:1.19<br/>
random-string-parameter:1.0<br/>
rebuild:338.va_0a_b_50e29397<br/>
release:2.19<br/>
remote-file:1.24<br/>
resource-disposer:0.25<br/>
role-strategy:756.v978cb_392eb_d3<br/>
run-condition:243.v3c3f94e46a_8b_<br/>
saferestart:102.v4dc1b_9636a_ee<br/>
saml:4.525.v4f6a_7209447e<br/>
scm-api:704.v3ce5c542825a_<br/>
script-security:1373.vb_b_4a_a_c26fa_00<br/>
sectioned-view:1.30<br/>
secure-requester-whitelist:72.v6cce468c5513<br/>
seed:2.1.4<br/>
shelve-project-plugin:3.3196.v0052de37a_8d3<br/>
show-build-parameters:1.0<br/>
sidebar-link:2.4.2<br/>
simple-build-for-pipeline:0.2<br/>
simple-theme-plugin:211.v5424a_5510e47<br/>
slave-setup:129.vee7cd5a_0e204<br/>
snakeyaml-api:2.3-125.v4d77857a_b_402<br/>
sse-gateway:1.28<br/>
ssh-agent:384.ve275343791a_6<br/>
ssh-credentials:355.v9b_e5b_cde5003<br/>
ssh-slaves:3.1031.v72c6b_883b_869<br/>
sshd:3.353.v2b_d33c46e970<br/>
statusmonitor:44.v3d97a_d2810f1<br/>
structs:343.vdcf37b_a_c81d5<br/>
subversion:1287.vd2d507146906<br/>
summary_report:1.15<br/>
test-stability:2.4<br/>
throttle-concurrents:2.16<br/>
timestamper:1.28<br/>
token-macro:444.v52de7e9c573d<br/>
trilead-api:2.209.v0e69b_c43c245<br/>
urltrigger:1.05<br/>
validating-string-parameter:255.v31e2e6d0d273<br/>
variant:70.va_d9f17f859e0<br/>
versioncolumn:320.v6b_b_814ca_01f7<br/>
view-job-filters:399.v6c89d5e6ff54<br/>
warnings-ng:12.5.0<br/>
webhook-step:342.v620877effe14<br/>
workflow-aggregator:608.v67378e9d3db_1<br/>
workflow-api:1371.ve334280b_d611<br/>
workflow-basic-steps:1079.vce64b_a_929c5a_<br/>
workflow-cps:4080.va_15b_44a_91525<br/>
workflow-durable-task-step:1405.v1fcd4a_d00096<br/>
workflow-job:1508.v9cb_c3a_a_89dfd<br/>
workflow-multibranch:806.vb_b_688f609ee9<br/>
workflow-scm-step:437.v05a_f66b_e5ef8<br/>
workflow-step-api:700.v6e45cb_a_5a_a_21<br/>
workflow-support:968.v8f17397e87b_8<br/>
ws-cleanup:0.48<br/>
xtrigger-api:1.2<br/>
xunit:3.1.5<br/>
zentimestamp:4.2
```
</details>
<details><summary><i>3 attachments</i></summary>

- [org-folder-job.png](https://raw.githubusercontent.com/jenkinsci/attachments-from-jira-issues-misc/refs/heads/main/attachments/64305/org-folder-job.png)
  > 
- [standalone-multibranch-pipeline.png](https://raw.githubusercontent.com/jenkinsci/attachments-from-jira-issues-misc/refs/heads/main/attachments/64306/standalone-multibranch-pipeline.png)
  > 
- [standalone-pipeline.png](https://raw.githubusercontent.com/jenkinsci/attachments-from-jira-issues-misc/refs/heads/main/attachments/64304/standalone-pipeline.png)
  > 
</details>

### PR DESCRIPTION
**Pull request by akash-manna-sky**
Quality gate "Reset" button not showing for jobs under GitHub Organization Folder

Fixes #3176 

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests that demonstrate the feature works or the issue is fixed

### CODE REVIEW

**Comment by akash-manna-sky** [comment]
Please review the changes. @uhafner

File: plugin/src/test/java/io/jenkins/plugins/analysis/core/model/ResetQualityGateCommandITest.java [hunk 1]
```diff
@@ -0,0 +1,106 @@
...
+import static org.assertj.core.api.Assertions.*;
+
+/**
+ * Integration tests for {@link ResetQualityGateCommand} with folder
+ * hierarchies. These tests verify that the folder plugin integration works
+ * correctly with real Jenkins instances.
+ *
+ * @author Akash Manna
+ */
+class ResetQualityGateCommandITest extends IntegrationTestWithJenkinsPerSuite {
```
Comment (uhafner) [inline plugin/src/test/java/io/jenkins/plugins/analysis/core/model/ResetQualityGateCommandITest.java]: The tests in this class basically test whether the parent child relationship works in Jenkins. This is already part of Jenkins core.

Can't you move these tests as a setup for the `ResetQualityGateCommandTest`?  Or alternatively, set permissions for the folders and jobs and see if it really works?

**Comment by akash-manna-sky** [comment]
Can you please review the changes? @uhafner

**Comment by akash-manna-sky** [comment]
Thanks!
